use crate::infrastructure::runtime::Wake;

#[cfg_attr(target_os = "linux", iced_layershell::to_layer_message(multi))]
#[derive(Debug, Clone)]
pub enum Message {
    Daemon(Wake),
    WindowOpened {
        id: iced::window::Id,
        width: f32,
        height: f32,
    },
    Viewport(f32, f32),
    MouseMoved(f32, f32),
    Click(f32, f32, crate::domain::input::MouseButton),
    Wheel(f32),
    KeyPrev,
    KeyNext,
    KeyFavourite,
    KeyFlip,
    KeyReveal,
    KeyEffects,
    KeyStudio,
    ApplyCurrent,
    SetColorFilter(i64),
    SetTypeFilter(String),
    SetFolder(String),
    CycleFolder {
        backwards: bool,
    },
    ToggleFolder,
    CycleType {
        backwards: bool,
    },
    CycleSort {
        backwards: bool,
    },
    CycleMode {
        backwards: bool,
    },
    ToggleHiddenFolders,
    SetSort(String),
    SetOrient(String),
    SetResolution(String),
    ToggleFavourites,
    ToggleFilterBar,
    BarHover(Option<usize>, Option<usize>),
    FolderMenuToggle,
    FolderMenuScroll(f32),
    ToggleSettings,
    Stash,
    ToggleAudio,
    Audio(crate::frontend::audio_panel::AudioMsg),
    ToggleAudioPanel,
    ToggleThemePanel,
    OpenThemeAudition,
    CloseThemeAudition,
    ThemeAuditionBackend(String),
    ThemeAuditionSelect {
        backend: String,
        key: String,
        value: String,
    },
    Theme(crate::frontend::theme_designer::ThemeMsg),
    TaskControl {
        id: String,
        action: crate::contracts::daemon::TaskControl,
    },
    MonFill(String, String),
    SetMods(crate::domain::input::Mods),
    PointerUp,
    KeyPressed(iced::keyboard::Key, iced::keyboard::Modifiers),
    ToggleEffects,
    Effects(crate::frontend::effects::EffectsMsg),
    Sched(crate::frontend::schedule_editor::SchedMsg),
    SceneProps(crate::frontend::scene_properties::ScenePropMsg),
    OpenSceneProps,
    ResetThumbnail(u32),
    SetViewMode(String),
    Settings(crate::frontend::settings::SettingsMsg),
    SemanticModelImported(
        Result<Option<crate::infrastructure::semantic_pack::ImportedSemanticPack>, String>,
    ),
    SemanticModelDeleted(String, Option<String>, Result<(), String>),
    SettingsPreviewAllocated(String, Option<iced_runtime::image::Allocation>),
    SetSettingsTab(String),
    ApplyPreset(String, String),
    SavePreset,
    PresetNameInput(String),
    DeletePreset(String, String),
    KeyUp,
    KeyDown,
    KeyPage {
        backwards: bool,
    },
    KeyEdge {
        last: bool,
    },
    Tag(crate::frontend::tagcloud::TagMsg),
    ToggleTagMode,
    MassTagInput(String),
    MassTagAdd(String),
    MassTagRemove(usize),
    MassTagApply,
    ToggleRandomRotate,
    ApplyRandom,
    OpenTagCloud,
    CloseTagCloud,
    PaneWheel(&'static str, f32),
    PaneScrolled(&'static str, f32, f32),
    ToggleHelp,
    ClearTags,
    OpenSourceBrowser,
    ToggleDownloads,
    OpenBrowser(String),
    CloseBrowser,
    OpenPlaylists,
    ClosePlaylists,
    Pl(crate::frontend::playlists::PlMsg),
    CardPicker(crate::frontend::playlists::CardPickerMsg),
    Browser(crate::frontend::browser::BrowserMsg),
    Noop,
    Exit,
}
